name: work_app
description: "A professional pay tracking application."
publish_to: 'none'
version: 1.0.62+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  provider: ^6.1.1 

  # --- Sync & Cloud Storage ---
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # --- Core Utilities ---
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  package_info_plus: ^8.0.0 
  flutter_app_installer: ^1.0.2
  
  # --- Network ---
  http: ^1.2.0
  dio: ^5.4.0

  # --- Audio & Multimedia ---
  audioplayers: ^5.2.1 

  # --- UI & Formatting ---
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  uuid: ^4.3.3
  
  # --- NEW PACKAGES ---
  share_plus: ^10.0.0  # For sharing files
  csv: ^6.0.0          # For generating CSV strings
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  
  # --- Testing Utilities ---
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/sounds/ 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/icon.png"