name: work_app
description: "A professional pay tracking application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI Icons
  cupertino_icons: ^1.0.8
  # Local Storage
  shared_preferences: ^2.5.1
  # Date Formatting
  intl: ^0.20.2
  # Unique IDs
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Register the assets folder so the app can see the icon file
  assets:
    - assets/

# Configuration for generating the App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  # This hex color matches your App Theme (Indigo)
  # It prevents the white border on some Android devices
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/icon.png"